# Generated by Django 4.0.6 on 2022-09-01 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_views_number'),
        ('blog', '0006_rename_category_post_categories'),
    ]

    operations = [
    ]
